routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/test', ['as' => 'test', 'uses' => 'CustomerAuth\RegisterController@test']);
Route::group(['middleware' => ['setTheme:default']], function () {
    Route::group(['namespace' => 'CustomerAuth','as' => 'customer.'], function () {
        Route::group(['middleware' => 'customer_guest'], function () {
            Route::get('/signup', ['as' => 'signup', 'uses' => 'RegisterController@showRegistrationForm']);
            Route::post('/customer_register', ['as' => 'register', 'uses' => 'RegisterController@register']);
            Route::get('/validate/otp', ['as' => 'otp.view', 'uses' => 'RegisterController@showOtp']);
            Route::post('/validate/otp', ['as' => 'validate.otp', 'uses' => 'RegisterController@validate_otp']);
            Route::post('/resend_otp', ['as' => 'resend.otp', 'uses' => 'RegisterController@resend_otp']);
            Route::get('/login', ['as' => 'login.view', 'uses' => 'LoginController@showLoginForm']);
            Route::post('/login', ['as' => 'login', 'uses' => 'LoginController@login']);
        });
        Route::group(['middleware' => 'customer_auth'], function() {
            Route::post('/customer_logout', ['as' => 'logout', 'uses' => 'LoginController@logout']);

        });
    });
    Route::group(['namespace' => 'front'], function () {
        Route::get('/', ['as' => 'index', 'uses'=> 'HomeController@index']);

        Route::group(['middleware' => 'customer_auth'], function () {
            Route::get('/details', ['as' => 'details', 'uses' => 'HomeController@details']);
            Route::get('/registration/complete', ['as' => 'customer.register.complete', 'uses'=> 'HomeController@signup_complete']);
            Route::post('/customer_register_s', ['as' => 'customer.register.second', 'uses' => 'HomeController@register_second']);
            Route::post('/customer_register_t', ['as' => 'customer.register.third', 'uses' => 'HomeController@register_third']);
        });
    });

});

resources/views/partial/compound_list.blade.php
@foreach($compounds as $compound)
    <div class="col-sm-6 fooReveal mb30">
        <div class="property-item">
            <div class="row">
                <div class="col-sm-6 p-r-0">
                    <figure>
                        <a href="#">
                            <img src="{{ \App\Website\Unit::DIR_IMAGE . $compound->first_image() }}" class="img-responsive" alt="Goeez">
                            <div class="overlay-prop">
                                <span><i class="fas fa-camera"></i>&nbsp; {{ $compound->images->count() }} photos</span>
                                <span><i class="fas fa-map-marker-alt"></i> &nbsp; {{$compound->property->district->name}}</span>
                            </div>
                        </a>
                    </figure>
                </div>
                <div class="col-sm-6">
                    <div class="detail">
                        <h3 class="price">SAR {{$compound->annual_rent}}</h3>
                        <h5>{{$compound->online_description}}</h5>
                        <div class="property-meta">
                            <span><i class="fas fa-bed"></i> 6</span>
                            <span><i class="fas fa-bath"></i> 5</span>
                            <span><i class="fas fa-car"></i> 4</span>
                            <span>Land Sze : {{$compound->total_area}} m<sup>2</sup></span>
                        </div>
                        <p>{{$compound->main_description}}
                        </p>
                        {{--<a class="more-details" href="{{ Auth::guard('web_customer')->guest() ? route('customer.login.view') : Auth::guard('web_customer')->user()->status!=1 ? route('customer.register.complete') : route('details') }}">More Details <i class="fas fa-caret-right"></i></a>--}}
                        <a class="more-details" href="{{ Auth::guard('web_customer')->guest() ? route('customer.login.view') : (Auth::guard('web_customer')->user()->status!=1 ? route('customer.register.complete') : route('details')) }}">More Details <i class="fas fa-caret-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <ul class="listings">
            <li class="arrow wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.1s" >
                <a href="">
                    <img src="{{ asset('assets/images/arrow-down.jpg') }}">
                    <i class="fab fa-facebook-f"></i>
                </a>
            </li>
            <li class="arrow wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.2s">
                <a href="">
                    <img src="{{ asset('assets/images/arrow-down.jpg') }}">
                    <i class="fab fa-twitter"></i>
                </a>
            </li>
            <li class="arrow wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.3s">
                <a href="">
                    <img src="{{ asset('assets/images/arrow-down.jpg') }}">
                    <i class="fab fa-whatsapp-square"></i>
                </a>
            </li>
            <li class="arrow wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.4s">
                <a href="">
                    <img src="{{ asset('assets/images/arrow-down.jpg') }}">
                    <i class="fab fa-linkedin-in"></i>
                </a>
            </li>
            <li class="arrow wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.5s">
                <a href="">
                    <img src="{{ asset('assets/images/arrow-down.jpg') }}">
                    <i class="fas fa-at"></i>
                </a>
            </li>
        </ul>
    </div>
@endforeach

resources/views/partial/login-modal.blade.php
<div class="modal fade" id="myLoginModal">
    <div class="modal-dialog ">
        <form class="login modal-content" action="{{ route('customer.login') }}" method="post" action='' id="login_form" role="form" data-plugin="ajaxForm">
            <!--<div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x</button>
                <h3>Login to MyWebsite.com</h3>
            </div>-->
            <div class="modal-body row" >
                <div class="close_btn">
                    <button type="button" class="close" data-dismiss="modal">✕</button>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12" style="padding: 12px 6%;">
                    <h2>Login</h2>
                    <p>Get Access to your account</p>
                </div>
                <div class="right-modal-content col-md-6 col-sm-12 col-xs-12" style="padding: 30px 2%;">
                    <div class="form-group @if ($errors->has('email')) has-error @endif">
                        <input type="text" name="email" id="email" placeholder="Email" />
                        @if ($errors->has('email'))
                        <span class="help-block">
                          {{ $errors->first('email') }}
                        </span>
                        @endif
                    </div>
                    <div class="form-group @if ($errors->has('password')) has-error @endif">
                        <input type="password" id="password" name="password" placeholder="Password" />
                        @if ($errors->has('password'))
                        <span class="help-block">
                            {{ $errors->first('password') }}
                        </span>
                        @endif
                    <input type="submit" value="Login" class="btn btn-lg" />
                    <a data-toggle="modal" href="#mySignupModal" class="btn btn-lg signup_button" >New to Kerala HealthMart? Sign up</a>
                    <div class="remember-forgot">
                        <div class="row">
                            <!--<div class="col-md-6">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" />
                                        Remember Me
                                    </label>
                                </div>
                            </div>-->
                            <div class="col-md-12 forgot-pass-content">
                                <a href="javascript:void(0)" class="forgot-pass pull-right">Forgot Password</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <!--<div class="modal-footer">
                New To MyWebsite.com?
                <a href="#" class="btn btn-primary">Register</a>
            </div>-->
        </form>
    </div>
</div>
@push('page_scripts')
<script>
    $(document).ready(function() {
        $('#myLoginModal').on('af.complete','#login_form',function(e,data) {
            $('#myLoginModal').modal('hide');
            location.reload();
        });

        var $validator = $('#login_form').validate({
            rules: {
                email: {
                    required: true,
                    email: true
                },
                password : {
                    required : true,
                    minlength: 6
                }
            },
            messages: {
                email: {
                    required: "Email is required"
                },
                password: {
                    required: "Password is required",
                    minlength: "Password must have 6 charecters"
                }
            }
        });


    });
</script>
@endpush

resources/views/partial/otp-modal.blade.php
<div class="modal fade" id="myOtpModal">
    <div class="modal-dialog ">
        {{--<form class="login modal-content" method="post" action='' name="login_form">--}}
        <form class="login modal-content" id="otp_verify_form" action="{{ route('customer.validate.otp') }}" method="POST" role="form" data-plugin="ajaxForm">
            <!--<div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x</button>
                <h3>Login to MyWebsite.com</h3>
            </div>-->
            <div class="modal-body row" >
                <div class="close_btn">
                    <button type="button" class="close" data-dismiss="modal">✕</button>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12" style="padding: 12px 6%;">
                    <h2>Enter OTP</h2>
                    <p>Check your Email / Mobile for OTP</p>
                </div>
                <div class="right-modal-content col-md-6 col-sm-12 col-xs-12" style="padding: 30px 2%;">
                    <div class="form-group @if ($errors->has('invalid_otp')) has-error @endif">
                        <input type="text" name="khm_otp" id="khm_otp" placeholder="Enter 6 digit OTP" />
                        @if ($errors->has('invalid_otp'))
                            <span class="help-block">
                              {{ $errors->first('invalid_otp') }}
                          </span>
                        @endif
                    </div>
                    <input type="submit" value="Submit" class="btn btn-lg" />
                    <div class="remember-forgot">
                        <div class="row">
                            <div class="col-md-12">
                                <small style="color:#f00"><a href="#">Resend OTP</a></small>
                            </div>
                            {{--<div class="col-md-12 forgot-pass-content">
                                <a href="javascript:void(0)" class="forgot-pass pull-right">Forgot Password</a>
                            </div>--}}
                        </div>
                    </div>
                </div>
            </div>
            <!--<div class="modal-footer">
                New To MyWebsite.com?
                <a href="#" class="btn btn-primary">Register</a>
            </div>-->
        </form>
    </div>
</div>
@push('page_scripts')
<script>
    $(document).ready(function() {
        $('#myOtpModal').on('af.success','#otp_verify_form',function(e,data) {
            $('#myOtpModal').modal('hide');
        }).on('af.error', function (e, responseText, textStatus, jqXHR, errorThrown) {
            if (jqXHR.status == 422) {
                responseText = $.parseJSON(responseText);
                var error = {};
                $.each(responseText, function (k, v) {
                    error[k] = v[0];
                });

                $validator.showErrors(error);
            } else {
                /*window.Site.toast.error("Some error occurred, Please try again");*/
            }
        });

        var $validator = $('#otp_verify_form').validate({
            rules: {
                'khm_otp': {
                    required: true
                }
            },
            messages: {
                'khm_otp': {
                    required: "Enter OTP"
                }
            }
        });
    });
</script>
@endpush

resources/views/partial/signup-modal.blade.php
<div class="modal fade" id="mySignupModal">
    <div class="modal-dialog ">
        {{--<form class="login modal-content" method="post" action='' name="login_form">--}}
        <form class="login modal-content" id="signup_form" action="{{ route('customer.register') }}" method="POST" role="form" data-plugin="ajaxForm">
            <!--<div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x</button>
                <h3>Login to MyWebsite.com</h3>
            </div>-->
            <div class="modal-body row" >
                <div class="close_btn">
                    <button type="button" class="close" data-dismiss="modal">✕</button>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12" style="padding: 12px 6%;">
                    <h2>Sign up</h2>
                    <p>We do not share your personal details with anyone</p>
                </div>
                <div class="right-modal-content col-md-6 col-sm-12 col-xs-12" style="padding: 30px 2%;">
                    {{--<div class="form-group @if ($errors->has('name')) has-error @endif">
                        <input type="text" name="name" id="name" placeholder="Name" />
                        @if ($errors->has('name'))
                            <span class="help-block">
                          {{ $errors->first('name') }}
                      </span>
                        @endif
                    </div>--}}
                    <div class="form-group @if ($errors->has('phone')) has-error @endif">
                        <input type="text" name="phone" id="phone" placeholder="Mobile Number" />
                        @if ($errors->has('phone'))
                            <span class="help-block">
                          {{ $errors->first('phone') }}
                      </span>
                        @endif
                    </div>
                    <div class="form-group @if ($errors->has('email')) has-error @endif">
                        <input type="text" name="email" id="email_su" placeholder="Email" />
                        @if ($errors->has('email'))
                            <span class="help-block">
                          {{ $errors->first('email') }}
                      </span>
                        @endif
                    </div>
                    <div class="form-group @if ($errors->has('password')) has-error @endif">
                        <input type="password" class="" id="password_su" name="password" placeholder="Password" />
                    </div>
                    <div class="form-group @if ($errors->has('password')) has-error @endif">
                        <input type="password" class="" id="password_confirmation" name="password_confirmation" placeholder="Re-enter Password" >
                        @if ($errors->has('password'))
                            <span class="help-block">
                          {{ $errors->first('password') }}
                      </span>
                        @endif
                    </div>
                    <input type="submit" value="Continue" class="btn btn-lg" />
                    {{--<a data-toggle="modal" href="#myLoginModal" class="btn btn-lg signup_button" >Existing User? Login</a>--}}
                    <div class="remember-forgot">
                        <div class="row">
                            <div class="col-md-12">
                                        <small style="color:#f00">*Email/Mobile Number is Mandatory</small>
                            </div>
                            {{--<div class="col-md-12 forgot-pass-content">
                                <a href="javascript:void(0)" class="forgot-pass pull-right">Forgot Password</a>
                            </div>--}}
                        </div>
                    </div>
                </div>
            </div>
            <!--<div class="modal-footer">
                New To MyWebsite.com?
                <a href="#" class="btn btn-primary">Register</a>
            </div>-->
        </form>
    </div>
</div>
@push('page_scripts')
<script>
    $(document).ready(function() {
        $('#mySignupModal').on('af.success','#signup_form',function(e,data) {
            $('#mySignupModal').modal('hide');
            $('#myOtpModal').modal('show');
        })

        jQuery.validator.addMethod("phoneno", function(phone_number, element) {
            phone_number = phone_number.replace(/\s+/g, "");
            return this.optional(element) || phone_number.length == 10 &&
                    phone_number.match(/^((\+[1-9]{1,4}[ \-]*)|(\([0-9]{2,3}\)[ \-]*)|([0-9]{2,4})[ \-]*)*?[0-9]{3,4}?[ \-]*[0-9]{3,4}?$/);
        }, "Enter valid phone number");
        var $validator = $('#signup_form').validate({
            rules: {
                email: {
                    required: true,
                    email: true
                },
                phone : {
                    required : true,
                    phoneno : true
                }
            },
            messages: {
                email: {
                    required: "Email is required"
                },
                phone: {
                    required: "Phone is required"
                }
            }
        });


    });
</script>
@endpush