routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/test', ['as' => 'test', 'uses' => 'CustomerAuth\RegisterController@test']);
Route::group(['middleware' => ['setTheme:default']], function () {
    Route::group(['namespace' => 'CustomerAuth','as' => 'customer.'], function () {
        Route::group(['middleware' => 'customer_guest'], function () {
            Route::get('/signup', ['as' => 'signup', 'uses' => 'RegisterController@showRegistrationForm']);
            Route::post('/customer_register', ['as' => 'register', 'uses' => 'RegisterController@register']);
            Route::get('/validate/otp', ['as' => 'otp.view', 'uses' => 'RegisterController@showOtp']);
            Route::post('/validate/otp', ['as' => 'validate.otp', 'uses' => 'RegisterController@validate_otp']);
            Route::post('/resend_otp', ['as' => 'resend.otp', 'uses' => 'RegisterController@resend_otp']);
            Route::get('/login', ['as' => 'login.view', 'uses' => 'LoginController@showLoginForm']);
            Route::post('/login', ['as' => 'login', 'uses' => 'LoginController@login']);
        });
        Route::group(['middleware' => 'customer_auth'], function() {
            Route::post('/customer_logout', ['as' => 'logout', 'uses' => 'LoginController@logout']);

        });
    });
    Route::group(['namespace' => 'front'], function () {
        Route::get('/', ['as' => 'index', 'uses'=> 'HomeController@index']);

        Route::group(['middleware' => 'customer_auth'], function () {
            Route::get('/details', ['as' => 'details', 'uses' => 'HomeController@details']);
            Route::get('/registration/complete', ['as' => 'customer.register.complete', 'uses'=> 'HomeController@signup_complete']);
            Route::post('/customer_register_s', ['as' => 'customer.register.second', 'uses' => 'HomeController@register_second']);
            Route::post('/customer_register_t', ['as' => 'customer.register.third', 'uses' => 'HomeController@register_third']);
        });
    });

});

resources/views/includes/compounds_section.blade.php
<div id="menu01" class="tab-pane fade in active">
    <section class="compound_wrapper">
        <div class="row ptb-50 fooContainer">
            <!--first property  -->
            <!--loop this column-->
            @include('partial.compound_list')
        </div>
    </section>
</div>

resources/views/includes/footer.blade.php
<section class="footer-wrapper" >
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="logo-description">
                    <img src="{{ asset('assets/images/W-LOGO.png') }}" alt="Goeez" class="logo">
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-4">
                <div class="logo-description">
                    <div class="des">
                        <p>
                            The company principle of Architecture-Studio
                            is the collective conception. From the very beginning, the practice has believed in the virtues
                            of exchange. crossing ideas, common effort, shared knowledge and enthusiasm.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-offset-4 col-lg-4">
                <div class="quick-contact">
                    <ul>
                        <li class="number"><a href="">+999999999999</a></li>
                        <li class="mail"><a href="mailto: customercare@riyalgold.com" target="_blank"> info@Goeez.com</a></li>
                        <li class="address">
                            Litaka, Jungmannova 35/29, <br>
                            Nove Me'sto,Czech Republic
                        </li>

                    </ul>
                    <div class="social-wrapper">
                        <ul class="list-inline">
                            <li><a href="" target="_blank">
                                    <img src="{{ asset('assets/images/FA.png') }}" alt="facebook">
                                </a></li>
                            <li><a href="" target="_blank">
                                    <img src="{{ asset('assets/images/INS.png') }}" alt="insta">
                                </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/includes/header.blade.php
<header class="top-header cbp-af-header">
    <nav class="navbar">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="./" class="logo"><img src="{{ asset('assets/images/logo.png') }}" alt="Goeez" class="img-logo"></a>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="./" class="active"> Individual</a></li>
                <li><a href="./"> Corporate</a></li>
                <li><a href="./"> About</a></li>
                <li><a href="./"> Contact</a></li>
                @if (Auth::guard('web_customer')->guest())
                    <li id="cust-signin" class="singn-in"><a href="{{ route('customer.login.view') }}"> Sign In</a></li>
                    <li id="cust-register" class="singn-in"><a href="{{ route('customer.signup') }}"> Register</a></li>
                @else
                    <li >
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            My Account <span class="caret"></span> </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                            <li><a tabindex="-1" href="#">Welcome {{ Auth::guard('web_customer')->user()->name }}</a></li>
                            <li><a tabindex="-1" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                                <form id="logout-form" action="{{ route('customer.logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endif

                <li id="logout-display" class="hidden" >
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        My Account <span class="caret"></span> </a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                        <li><a tabindex="-1" href="#">Welcome</a></li>
                        <li><a tabindex="-1" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                            <form id="logout-form" action="{{ route('customer.logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </li>

            </ul>

        </div><!--/.nav-collapse -->
    </nav>
</header>
@push('page_style')
<style>
    .nav .open>a, .nav .open>a:focus, .nav .open>a:hover
</style>
@endpush

resources/views/includes/management_services_section.blade.php
<div id="menu21" class="tab-pane fade">
    <div class="row ptb-50">
        <div class="col-sm-4">
            <div class="image-tile"><img src="{{ asset('assets/images/2.jpg') }}" alt="goeez" class="img-responsive"></div>
        </div>
        <div class="col-sm-4">
            <div class="image-tile"><img src="{{ asset('assets/images/3.jpg') }}" alt="goeez" class="img-responsive"></div>
        </div>
        <div class="col-sm-4">
            <div class="image-tile"><img src="{{ asset('assets/images/1.jpg') }}" alt="goeez" class="img-responsive"></div>
        </div>
    </div>
</div>

resources/views/includes/relocation_services_section.blade.php
<div id="menu11" class="tab-pane fade">
    <section class="relocation-wrapper">
        <div class="row">
            <div class="col-sm-4">
                <div class="image-tile">
                    <a href="./relocating.php" class="img">
                        <img src="{{ asset('assets/images/i-r.png') }}" alt="goeez" class="img-responsive">
                    </a>
                    <div class="title_thumbs text-center">
                        I'm Relocating
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="image-tile text-center">
                    <a href="./relocating.php" class="img">
                        <img src="{{ asset('assets/images/c-r.png') }}" alt="goeez" class="img-responsive">
                    </a>
                    <div class="title_thumbs">
                        Corporate Relocation
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="image-tile text-center">
                    <a href="./relocating.php" class="img">
                        <img src="{{ asset('assets/images/a-f-r-c.png') }}" alt="goeez" class="img-responsive">
                    </a>
                    <div class="title_thumbs">
                        Assistance for Relocation Companies
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="description_wrapper">
                    <p>
                        Whether you are a Corporate Company, Individual or an International Relocation Services Company,
                        we have many things to offer you. Being the Pioneer in Relocation Consultancy Services provider in this local market,
                        and the one and professional services company, we have much reliable and professional services to offer you.
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="image-tile">
                    <a href="./relocating.php" class="img">
                        <img src="{{ asset('assets/images/l-f-h.png') }}" alt="goeez" class="img-responsive">
                    </a>
                    <div class="title_thumbs">
                        I'm looking for a home
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="image-tile text-center">
                    <a href="./relocating.php" class="img">
                        <img src="{{ asset('assets/images/l-f-c.png') }}" alt="goeez" class="img-responsive">
                    </a>
                    <div class="title_thumbs">
                        I'm looking for a Compound
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="image-tile text-center">
                    <a href="./relocating.php" class="img">
                        <img src="{{ asset('assets/images/i-n-p-a.png') }}" alt="goeez" class="img-responsive">
                    </a>
                    <div class="title_thumbs">
                        I need personalized assistance
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="description_wrapper">
                    <p>
                        Whether you are a Corporate Company, Individual or an International Relocation Services Company,
                        we have many things to offer you. Being the Pioneer in Relocation Consultancy Services provider in this local market,
                        and the one and professional services company, we have much reliable and professional services to offer you.
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="image-tile text-center">
                    <a href="./relocating.php" class="img">
                        <img src="{{ asset('assets/images/s-i-s.png') }}" alt="goeez" class="img-responsive">
                    </a>
                    <div class="title_thumbs">
                        Settle-in Services
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="image-tile text-center">
                    <a href="./relocating.php" class="img">
                        <img src="{{ asset('assets/images/s-s-s.png') }}" alt="goeez" class="img-responsive">
                    </a>
                    <div class="title_thumbs">
                        School Search Support
                    </div>
                </div>

            </div>
            <div class="col-sm-4">
                <div class="image-tile text-center">
                    <a href="./relocating.php" class="img">
                        <img src="{{ asset('assets/images/o-t-.png') }}" alt="goeez" class="img-responsive">
                    </a>
                    <div class="title_thumbs">
                        Orientation Tours
                    </div>
                </div>
            </div>
        </div>
        <!--enquiry form-->
        <div class="row">
            <div class="col-sm-12">
                <div class="enquiry_wrapper">
                    <div class="title_contact">
                        <h1>Make an Enquiry</h1>
                    </div>
                    <div class="contact-form">
                        <div class="form-wrapper">
                            <form class="form"  id="contact-form" method="post" action="" role="form">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control custom-control" id="form_name" name="name" placeholder=" Name">
                                            <div class="help-block with-errors"></div>
                                        </div>

                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <input type="email" class="form-control custom-control" id="mobile" name="mobile" placeholder="Phone">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <input type="email" class="form-control custom-control" id="mobile" name="mobile" placeholder="Mail">
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <select class="form-control" id="sel1">
                                                <option selected="selected">Choose your service</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-10">
                                        <div class="form-group">
                                            <textarea class="custom-control" rows="2" name="message" id="form_message" placeholder="Message"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="btn-wrapper">
                                            <button type="submit" class="submit-btn" id="submit">Send</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>